Etl kan 175
KamaTechOrg/KT_Cloud pull request #166
Opened 2024-09-08 14:17 UTC by Tem-M

daily etl handles changes incrementally
weekly etl handles changes non-incrementally

2024-09-08 14:40 UTC, riki7649255 requested changes
1. remove tha "-kan175" string from both file names
2. DB/ETLS/AlbumDaily-kan175.py -> etl_table_name = 'daily_album_etl'
change the target table name to be 'daily_album' without the etl part, we use it mainly in view names that store the ETL logic
3. please add documentation and explain above each code snippet what it perform
4. I did not check the commented code at all but I dont think it is the incremental mode tomorrow we will talk about it and then you will fix it or remove
 please do all the above for noth files

looking great, good job!

2024-09-08 18:15 UTC, Tem-M commented
> 1. remove tha "-kan175" string from both file names
> 2. DB/ETLS/AlbumDaily-kan175.py -> etl_table_name = 'daily_album_etl'
>    change the target table name to be 'daily_album' without the etl part, we use it mainly in view names that store the ETL logic
> 3. please add documentation and explain above each code snippet what it perform
> 4. I did not check the commented code at all but I dont think it is the incremental mode tomorrow we will talk about it and then you will fix it or remove
>    please do all the above for noth files
> 
> looking great, good job!

changes applied

2024-09-09 06:12 UTC, riki7649255 approved these changes

2024-09-09 06:13 UTC, Mychaly approved these changes

2024-09-09 06:14 UTC, shana9317 approved these changes

2024-09-09 06:14 UTC, merged