Lock model controller
KamaTechOrg/KT_Cloud pull request #327
Opened 2024-09-18 10:15 UTC by tamar1225

Model, Controller and Service that manages:
object locks, including creation, deletion.
And also a parallel thread that run in the background for monitoring the time limit of the locks and deleting those that have expired.

2024-09-18 10:16 UTC, saraNoigershel approved these changes

2024-09-18 10:17 UTC, yael-git10 approved these changes

2024-09-18 10:23 UTC, ShaniStrassProg approved these changes

2024-09-18 11:55 UTC, riki7649255 reviewed
DB/NEW_KT_DB/DataAccess/DBManager.py
1.  line 26- why do we need this None assignment?
2. did you verify that when selecting records, no need to commit?
3. please create generic function for internal use- close_connection() that will contain this: if connection:
                connection.close()
(avoid duplicative code)

DB/NEW_KT_DB/DataAccess/ObjectManager.py
4. discard changes

Storage/NEW_KT_Storage/Controller/LockController.py
5. line 3- use relative path and not local full
6. line 10- add 2 empty lines and remove the 2 empty line from after the function definition
7. can_update_object() => lets think on another name. explain to me what is the purpose of this function and we'll think together. do so for can_dalata_object.
maybe is_object_deleteable ? check if its valid syntax
8. remove the main block- save it locally you will need it for intergration

Storage/NEW_KT_Storage/DataAccess/LockManager.py
9. change full local path
10. you dont need create_table function, only to call create management table from init() method, also add table_structure to the model and use it from there

Storage/NEW_KT_Storage/DataAccess/ObjectManager.py
11. discard changes

Storage/NEW_KT_Storage/Models/LockModel.py
12. replace local full path with relative

Storage/NEW_KT_Storage/Service/Classes/LockService.py
13. replace local full path with relative
14. def calculate_retention_duration=> Im not sure this is good name. what does this function do?
15. can_update_object() + can_delete_object() => rename

2024-09-18 13:21 UTC, tamar1225 commented
@riki7649255 
7. def can_delete_object and def can_update_object are used to check check whether changes can be made to an object. They get a name in an act and an object and check if there is a lock for this file.
The BUCKET or OBJECT class will be able to use these functions to check whether it is possible to make changes such as deleting or creating an object according to its lock if it exists.
15 Rename to what?

2024-09-18 19:12 UTC, riki7649255 requested changes
few leftovers:

Storage/NEW_KT_Storage/Controller/LockController.py
1. rename can_delete_object() to is_object_deleteable(), and can_update_object() to is_object_updateable() (also inside the function when calling the service action)

Storage/NEW_KT_Storage/DataAccess/LockManager.py
2. line 13- you dont need to assign model.table_structure to a new variable, use it directly inside the create_managment_table
3. remove the create_table() function
4. change full local path

Storage/NEW_KT_Storage/Service/Classes/LockService.py
5. rename can_delete_object() to is_object_deleteable(), and can_update_object() to is_object_updateable()

2024-09-19 06:00 UTC, riki7649255 approved these changes

2024-09-19 06:06 UTC, merged