lifecycle policy
KamaTechOrg/KT_Cloud pull request #330
Opened 2024-09-18 11:22 UTC by efrat7248

2024-09-18 20:05 UTC, riki7649255 requested changes
DB/NEW_KT_DB/DataAccess/ObjectManager.py
1. discard changes

Storage/NEW_KT_Storage/Controller/LifecyclePolicyController.py
2. remove main() block- save it locally you will use it for integration

Storage/NEW_KT_Storage/DataAccess/LifecyclePolicyManager.py
3. replace full local path with relative
4. you dont need the create_table() function- remove it, and call to object_manager.create_managment_table() inside the init. put the table_columns as table_structure attribute in the model, among with object_name from the manager service init() method
5. in documentation you used the term "physical object"- replace it with "policy file" in all places

Storage/NEW_KT_Storage/DataAccess/StorageManager.py
6. rename read_json() to read_json_file(), and write_json() to write_to_json_file()- you could look at another function names and copy convention

7. most important!!!
you put all logic in your manager instead of in your sevice
for example the file creation for plicy. please fix

2024-09-20 14:04 UTC, riki7649255 requested changes
Storage/NEW_KT_Storage/DataAccess/LifecyclePolicyManager.py
1. replace full local path with relative
2. still one place here uses the term "physical"- remove it, also in your service one more place.

Storage/NEW_KT_Storage/DataAccess/StorageManager.py
3. rename write_json() to write_to_json_file()

2024-09-21 17:21 UTC, riki7649255 requested changes
rename read_to_json_file() to read_json_file()

2024-09-21 17:27 UTC, riki7649255 approved these changes

2024-09-21 17:30 UTC, rachel-8511 approved these changes

2024-09-21 17:30 UTC, ShaniStrassProg approved these changes

2024-09-21 17:31 UTC, merged