Write more test & use my exeption
KamaTechOrg/KT_Cloud pull request #337
Opened 2024-09-18 14:15 UTC by Malki1844

I wrote more tests and added error typing
(There are changes in this code because of the tests..)

@riki7649255

2024-09-18 19:31 UTC, riki7649255 requested changes
Storage/NEW_KT_Storage/Service/Classes/BucketService.py
1. dont you need to call object_manager.create_management_table() inside the init() method? if so, please declare table_structure attribute inside the model

your tests file is very impressive, also the validation and exceptions. well dine!

2024-09-19 05:57 UTC, riki7649255 requested changes
you dont need the create_table() function.
move the managment table creation to the init() model of the service.
remove the def create_table() from the manager.

2024-09-19 06:41 UTC, riki7649255 approved these changes

2024-09-19 06:43 UTC, yehudit-9016 approved these changes

2024-09-19 06:43 UTC, leah-bellahsen-git approved these changes
good

2024-09-19 06:51 UTC, rachel-8511 approved these changes

2024-09-19 08:21 UTC, merged