Event subscription final
KamaTechOrg/KT_Cloud pull request #343
Opened 2024-09-18 23:21 UTC by eti-youngreis

2024-09-19 06:10 UTC, riki7649255 requested changes
DB/NEW_KT_DB/DataAccess/EventSubscriptionManager.py
1. line 13- send the 'text' parameter with assignment: pk...='text' so it will be clear and understood
2. modifyEventSubscription()- add documentation, same for describeEventSubscriptionByCriteria()

DB/NEW_KT_DB/Models/EventSubscriptionModel.py
3. you used but not declared attribute table_schema.

DB/NEW_KT_DB/Service/Classes/EventSubscriptionService.py
4. add docimentation

SNS/DataAccess/SNSManager.py
5. rename is_exist_topic() to is_topic_exist()- in all references (invalid syntax)
6. add documentation

2024-09-20 14:00 UTC, riki7649255 requested changes
DB/NEW_KT_DB/Test/GeneralTests.py
1. lets rename function is_object_equal() to are_objects_equal()

2024-09-21 19:22 UTC, riki7649255 approved these changes

2024-09-21 19:26 UTC, sarit-r approved these changes

2024-09-21 19:26 UTC, rachel-8511 approved these changes

2024-09-21 19:27 UTC, merged